---
title: "Committee Meeting Follow-ups"
author: "Windy Wang"
date: "January 31, 2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

library(dplyr)

ds <- readRDS(file='../data/ds.Rds') %>% 
  dplyr::mutate(logUdbpRatio = log(udbpCrRatio)) %>% 
  dplyr::select(SID, VN, fVN, Age, ACR, eGFR, UDBP,
                acr_status, eGFR_status, UDBP_status, 
                udbpCrRatio, logUdbpRatio)
  # dplyr::group_by(SID) %>% 
  # dplyr::filter(n() == 3) %>% 
  # dplyr::ungroup()

ds1 <- ds %>% 
  dplyr::filter(fVN == "Baseline")

source('../R/functions.r')
source("../R/graphs.R")
```

### UDBP Distribution

Distribution of urinary VDBP (not log adjusted)

```{r distribution}
ds %>%
  histo_plot("UDBP", 20, 'Urinary VDBP (ng/mL)',
             facet = TRUE)
```

Distribution of urinary VDBP (adjusted using natural log)
 
```{r log distribution}
ds %>%
  histo_plot("log(UDBP)", .2, 'log Urinary VDBP (ng/mL)',
             facet = TRUE)
```

<!-- ### Age-ACR Associations -->

<!-- ```{r age-ACR} -->
<!-- ds %>% -->
<!--   scatter_plot("Age", "log(ACR)", -->
<!--                "Age (Years)", "log Urine Albumin-to-Creatinine Ratio (mg/mmol)", -->
<!--                facet = TRUE) -->
<!-- ``` -->

<!-- At baseline, there is a significant positive association.  -->
<!-- ```{r age-ACR-stats1} -->
<!-- ds %>%  -->
<!--   filter(fVN == "Baseline") %>%  -->
<!--   cor.test(formula = ~ Age + log(ACR), data = ., method = "spearman") -->
<!-- ``` -->

<!-- At 3 year, there is a significant positive association -->
<!-- ```{r age-ACR-stats2} -->
<!-- ds %>%  -->
<!--   filter(fVN == "3Year") %>%  -->
<!--   cor.test(formula = ~ Age + log(ACR), data = ., method = "spearman") -->
<!-- ``` -->
<!-- At 6 year, there is significant positive association -->
<!-- ```{r age-ACR-stats6} -->
<!-- ds %>%  -->
<!--   filter(fVN == "6Year") %>%  -->
<!--   cor.test(formula = ~ Age + log(ACR), data = ., method = "spearman") -->
<!-- ``` -->

<!-- ### Age-eGFR Associations -->

<!-- ```{r age-eGFR} -->
<!-- ds %>%  -->
<!--   scatter_plot("Age",  -->
<!--                "eGFR", -->
<!--                "Age (Years)",  -->
<!--                "Estimated Glomerular Filtration Rate (ml/min/1.73m^2)", -->
<!--                facet = TRUE) -->
<!-- ``` -->

<!-- At baseline, there is a significant positive association. -->
<!-- ```{r age-eGFR-stats1} -->
<!-- ds %>%  -->
<!--   filter(fVN == "Baseline") %>%  -->
<!--   cor.test(formula = ~ Age + eGFR, data = ., method = "pearson") -->
<!-- ``` -->

<!-- At 3 year, there is a significant positive association -->
<!-- ```{r age-eGFR-stats3} -->
<!-- ds %>%  -->
<!--   filter(fVN == "3Year") %>%  -->
<!--   cor.test(formula = ~ Age + eGFR, data = ., method = "pearson") -->
<!-- ``` -->
<!-- At 6 year, there is significant positive association -->
<!-- ```{r age-eGFR-stats6} -->
<!-- ds %>%  -->
<!--   filter(fVN == "6Year") %>%  -->
<!--   cor.test(formula = ~ Age + eGFR, data = ., method = "pearson") -->
<!-- ``` -->
